// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSPNYZSXOmA-o1QWGLRuwXLkpRw3_aaQ',
    appId: '1:1081363475363:web:7143f37a912d281e664816',
    messagingSenderId: '1081363475363',
    projectId: 'broker-32024',
    authDomain: 'broker-32024.firebaseapp.com',
    databaseURL: 'https://broker-32024-default-rtdb.firebaseio.com',
    storageBucket: 'broker-32024.firebasestorage.app',
    measurementId: 'G-GVWTG15BYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgf1uu7c31-3_yAmZx-YAKuli6GkWuE0I',
    appId: '1:1081363475363:android:bfcad91a5d727da1664816',
    messagingSenderId: '1081363475363',
    projectId: 'broker-32024',
    databaseURL: 'https://broker-32024-default-rtdb.firebaseio.com',
    storageBucket: 'broker-32024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEaYSI5OYV70eH0A5iJ8gpIzeAUpotkXo',
    appId: '1:1081363475363:ios:d473526dc8424c74664816',
    messagingSenderId: '1081363475363',
    projectId: 'broker-32024',
    databaseURL: 'https://broker-32024-default-rtdb.firebaseio.com',
    storageBucket: 'broker-32024.firebasestorage.app',
    iosBundleId: 'com.devright.broker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEaYSI5OYV70eH0A5iJ8gpIzeAUpotkXo',
    appId: '1:1081363475363:ios:d473526dc8424c74664816',
    messagingSenderId: '1081363475363',
    projectId: 'broker-32024',
    databaseURL: 'https://broker-32024-default-rtdb.firebaseio.com',
    storageBucket: 'broker-32024.firebasestorage.app',
    iosBundleId: 'com.devright.broker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdvPkau6WqImmXSIArlrdDLEfLzBSG2yU',
    appId: '1:1081363475363:web:96c01b4b547b4f7f664816',
    messagingSenderId: '1081363475363',
    projectId: 'broker-32024',
    authDomain: 'broker-32024.firebaseapp.com',
    databaseURL: 'https://broker-32024-default-rtdb.firebaseio.com',
    storageBucket: 'broker-32024.firebasestorage.app',
    measurementId: 'G-TPXHYY42EP',
  );
}
