part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const home = _Paths.home;
  static const notification = _Paths.notification;
  static const searchByFilter = _Paths.searchByFilter;
  static const search = _Paths.search;
  static const brokerPoints = _Paths.brokerPoints;
  static const userInformation = _Paths.userInformation;
  static const contactUs = _Paths.contactUs;
  static const addProperty = _Paths.addProperty;
  static const propertyDetails = _Paths.propertyDetails;
  static const addApartment = _Paths.addApartment;
  static const addApartmentStage2 = _Paths.addApartmentStage2;
  static const addApartmentStage3 = _Paths.addApartmentStage3;
  static const addApartmentStage4 = _Paths.addApartmentStage4;
  static const addApartmentStage5 = _Paths.addApartmentStage5;
  static const addApartmentStage6 = _Paths.addApartmentStage6;
  static const editApartment = _Paths.editApartment;
  static const editApartmentStage2 = _Paths.editApartmentStage2;
  static const editApartmentStage3 = _Paths.editApartmentStage3;
  static const editApartmentStage4 = _Paths.editApartmentStage4;
  static const editApartmentStage5 = _Paths.editApartmentStage5;
  static const editApartmentStage6 = _Paths.editApartmentStage6;
  static const paymentStage = _Paths.paymentStage;
  static const premiumPaymentStage = _Paths.premiumPaymentStage;
  static const editPremiumPaymentStage = _Paths.editPremiumPaymentStage;
  static const editPaymentStage = _Paths.editPaymentStage;
  static const splash = _Paths.splash;
  static const noInternet = _Paths.noInternet;
  static const onBording = _Paths.onBording;
  static const signIn = _Paths.signIn;
  static const verification = _Paths.verification;
  static const signUpVerification = _Paths.signUpVerification;
  static const changePassword = _Paths.changePassword;
  static const forgetPassword = _Paths.forgetPassword;
  static const verifyForgetPassword = _Paths.verifyForgetPassword;
  static const createAccount = _Paths.createAccount;
  static const signUp = _Paths.signUp;
  static const personalData = _Paths.personalData;
}

abstract class _Paths {
  _Paths._();
  static const home = '/home';
  static const noInternet = '/noInternet';
  static const notification = '/notification';
  static const searchByFilter = '/searchByFilter';
  static const search = '/search';
  static const brokerPoints = '/brokerPoints';
  static const userInformation = '/userInformation';
  static const contactUs = '/contactUs';
  static const addProperty = '/addProperty';
  static const propertyDetails = '/propertyDetails';
  static const addApartment = '/AddApartment';
  static const addApartmentStage2 = '/AddApartmentStage2';
  static const addApartmentStage3 = '/AddApartmentStage3';
  static const addApartmentStage4 = '/AddApartmentStage4';
  static const addApartmentStage5 = '/AddApartmentStage5';
  static const addApartmentStage6 = '/AddApartmentStage6';
  static const editApartment = '/editApartment';
  static const editApartmentStage2 = '/editApartmentStage2';
  static const editApartmentStage3 = '/editApartmentStage3';
  static const editApartmentStage4 = '/editApartmentStage4';
  static const editApartmentStage5 = '/editApartmentStage5';
  static const editApartmentStage6 = '/editApartmentStage6';
  static const paymentStage = '/paymentStage';
  static const premiumPaymentStage = '/premiumPaymentStage';
  static const editPremiumPaymentStage = '/editPremiumPaymentStage';
  static const editPaymentStage = '/editPaymentStage';
  static const splash = '/splash';
  static const onBording = '/on-bording';
  static const signIn = '/sign-in';
  static const verification = '/verification';
  static const signUpVerification = '/signUpVerification';
  static const changePassword = '/change-password';
  static const forgetPassword = '/forget-password';
  static const verifyForgetPassword = '/verify-forget-password';
  static const createAccount = '/create-account';
  static const signUp = '/sign-up';
  static const personalData = '/personal-data';
}
